name: Task
description: Create a task.
title: "[Task]: "
body:
  - type: input
    id: summary
    attributes:
      label: Brief Summary
      description: Provide a brief summary of the task.
      placeholder: ex. Implement feature X
    validations:
      required: true
